apiVersion: 1

datasources:
  - name: Prometheus-muhammad_ivan_LspW
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
